### PR TITLE
Feature: Generate Template Screenshots

### PR DESCRIPTION
**Pull request by QuinnRhys89**
### WHY

Generated screenshots at three different viewport sizes (desktop, tablet, mobile) for each template.

Reference: https://docs.google.com/document/d/1vNYhER1MeU-qImV4PkPP7wqg0BLFjUPZYRzH_9757Js/edit

## Note

There are a some outliers that didn't capture correctly using url2png:

- [x] Discover_Pets
- [x] Discover_Wedding
- [x] Explorer_Landscape
- [x] Savannah_Fine_Art
- [x] Savannah_Portrait
- [x] Southwest_Portrait

### CODE REVIEW

**Comment by turbobeast** [comment]
🤔 nice work... but I'm not sure if this repo is the right place to store these screenshots..

**Comment by QuinnRhys89** [comment]
@turbobeast Maybe we won't merge this branch... I thought it would be easier for @SCR-TON to grab the screenshots this way? Suggestions?

**Comment by turbobeast** [comment]
@SCR-TON can grab them from this branch now.

Have you considered cyberduck?  😛

**Comment by turbobeast** [comment]
Screenshots can be found at https://drive.google.com/drive/folders/1UkfYQKuZjsvuxy-pzd1kEH1Y7L9OUilK?usp=sharing

**Pull request closed without merging**
